#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99
STOP=99

service_triggers() {
    procd_add_reload_trigger "network"
    procd_add_reload_trigger "cake_secondwan"
}

start_service() {
    /etc/init.d/cake enabled || exit 0
    logger -t cake "Starting CAKE for secondwan"
    sh /etc/script/cake-tune.sh
}

stop_service() {
    echo stop

    ### Interface ###
    WAN=$(uci -q get cake_secondwan.global.wan_iface || echo "lan1")
    IFB=$(uci -q get cake_secondwan.global.ifb_iface || echo "ifb-lan1")

    tc qdisc del dev $WAN root > /dev/null 2>&1
    tc qdisc del dev $IFB root > /dev/null 2>&1
    tc qdisc del dev $WAN ingress > /dev/null 2>&1
    ip link del $IFB 2>/dev/null

    sysctl -w net.core.default_qdisc=fq_codel > /dev/null 2>&1
    sysctl -w net.ipv4.tcp_congestion_control=cubic > /dev/null 2>&1
    sysctl -w net.ipv4.tcp_ecn=2 > /dev/null 2>&1

    exit 0
}

restart() {
    echo "Restarting service..."
    /etc/init.d/cake stop
    sleep 1
    /etc/init.d/cake start
}

reload_service() {
    restart
}
